name: Linux NoAVX Build
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/linux-noavx-build.yml'

jobs:
  linux-noavx-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.2
          path: whisper.cpp

      - name: Install cross-compilation toolchains
        run: |
          sudo apt-get update 
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Build Linux NoAVX Libraries
        run: make linux_noavx

      - name: Upload Linux NoAVX Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-noavx-build
          path: runtimes/linux-*_noavx/*
          retention-days: 7
