name: Linux CUDA Build
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/linux-cuda-build.yml'

jobs:
  linux-cuda-build:
    runs-on: ubuntu-latest

    container: nvidia/cuda:11.8.0-devel-ubuntu22.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.2
          submodules: true

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y cmake build-essential

      - name: Build Linux CUDA Libraries
        run: make linux_cuda

      - name: Upload Linux CUDA Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-cuda-build
          path: runtimes/linux-*_cuda/*
          retention-days: 7
