name: Linux CUDA Build
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/linux-cuda-build.yml'

jobs:
  linux-cuda-build:
    runs-on: ubuntu-latest

    container: nvidia/cuda:11.8.0-devel-ubuntu22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.2
          path: whisper.cpp

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y cmake build-essential

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.5.0'
          method: 'network'

      - name: Build Linux CUDA Libraries
        run: make linux_cuda

      - name: Upload Linux CUDA Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-cuda-build
          path: runtimes/linux-*_cuda/*
          retention-days: 7
