name: Linux Native Build (with container)
on:
  workflow_dispatch:
  workflow_call:

jobs:
  linux-native-build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Checkout whisper.cpp
          uses: actions/checkout@v4
          with:
            repository: ggerganov/whisper.cpp
            ref: v1.7.2
            path: whisper.cpp

        - name: Build Docker Image
          run: docker build -t linux-native-build -f linux-Dockerfile .

        - name: Create output directory
          run: mkdir -p ./artifacts

        - name: Run Build in Docker Container
          run: |
            docker run --rm \
              -v $(pwd):/build \
              -v $(pwd)/artifacts:/build/runtimes \
              linux-native-build

        - name: Upload Linux Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: linux-build
            path: ./artifacts
            retention-days: 7
