name: MacOS Native Build
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'macos-native-build.yml'

jobs:
  macos-native-build:
    strategy:
      matrix:
        include:
          - runner: macos-13  # Intel
            arch: x64
          - runner: macos-14  # Apple Silicon
            arch: arm64

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.2
          path: whisper.cpp

      - name: Build MacOS Libraries
        run: make macos_${{ matrix.arch }}

      - name: Upload Mac Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-${{ matrix.arch }}-build
          path: runtimes/macos-${{ matrix.arch }}/*
          retention-days: 7
