name: MacOS Native Build
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'macos-native-build.yml'

jobs:
  macos-native-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.2
          path: whisper.cpp

      - name: Install build dependencies
        run: brew install coreutils cmake

      - name: Build MacOS Libraries
        run: make macos

      - name: Upload Mac Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: runtimes/macos-*/*
          retention-days: 7
