name: Windows Native Build
on:
  workflow_dispatch:
  workflow_call:


jobs:
  windows-native-build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: whisper.php

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.2
          path: whisper.cpp

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Run build script
        run: |
          cd whisper.php
          .\scripts\build.bat cpu ..\whisper-cpp\
          cd ${{ github.workspace }}\whisper-cpp\build\bin\Release
          ren whisper.dll libwhisper.dll

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: whisper-cpp/build/bin/Release/libwhisper.dll
